# Generated by Django 4.2 on 2023-04-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='Pics', max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('add', models.TextField()),
                ('pincode', models.IntegerField()),
                ('adm', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=50)),
                ('img', models.ImageField(default='Pics', upload_to='Media')),
            ],
        ),
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=50)),
                ('file', models.FileField(default='File', upload_to='Pdf Folder')),
            ],
        ),
    ]
